name: thy_pace_mobile
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.10.7

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  go_router: ^17.2.0
  audioplayers: ^6.6.0
  flutter_svg: ^2.0.10+1
  xml: ^6.5.0
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/menu/
    - assets/audio/
    - assets/audio/direction/
    - assets/audio/row/
    - assets/images/house/
    - assets/images/house/animation/
    - assets/images/house/double/
    - assets/images/house/double/double_3/
    - assets/images/house/double/double_3_fake/
    - assets/images/house/double/double_4/
    - assets/images/house/double/double_4_fake/
    - assets/images/house/double/double_5/
    - assets/images/house/double/double_5_fake/
    - assets/images/house/double/double_6/
    - assets/images/house/double/double_6_fake/
    - assets/images/house/double/double_7/
    - assets/images/house/double/double_7_fake/
    - assets/images/house/single/
    - assets/images/house/single/single_3/
    - assets/images/house/single/single_3_fake/
    - assets/images/house/single/single_4/
    - assets/images/house/single/single_4_fake/
    - assets/images/house/single/single_5/
    - assets/images/house/single/single_5_fake/
    - assets/images/house/single/single_6/
    - assets/images/house/single/single_6_fake/
    - assets/images/house/single/single_7/
    - assets/images/house/single/single_7_fake/
    - assets/images/house/triple/
    - assets/images/house/triple/triple_3/
    - assets/images/house/triple/triple_3_fake/
    - assets/images/house/triple/triple_4/
    - assets/images/house/triple/triple_4_fake/
    - assets/images/house/triple/triple_5/
    - assets/images/house/triple/triple_5_fake/
    - assets/images/house/triple/triple_6/
    - assets/images/house/triple/triple_6_fake/
    - assets/images/house/triple/triple_7/
    - assets/images/house/triple/triple_7_fake/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
